[2022-10-22 08:14:04,707] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: target_ingest_dag.source_ingest_sensor scheduled__2022-10-22T07:05:00+00:00 [queued]>
[2022-10-22 08:14:04,724] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: target_ingest_dag.source_ingest_sensor scheduled__2022-10-22T07:05:00+00:00 [queued]>
[2022-10-22 08:14:04,725] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-10-22 08:14:04,726] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2022-10-22 08:14:04,727] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-10-22 08:14:04,743] {taskinstance.py:1377} INFO - Executing <Task(ExternalTaskSensor): source_ingest_sensor> on 2022-10-22 07:05:00+00:00
[2022-10-22 08:14:04,749] {standard_task_runner.py:52} INFO - Started process 201 to run task
[2022-10-22 08:14:04,753] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'target_ingest_dag', 'source_ingest_sensor', 'scheduled__2022-10-22T07:05:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/target_ingest_dag.py', '--cfg-path', '/tmp/tmpgpdgey9a', '--error-file', '/tmp/tmpr_5f74hi']
[2022-10-22 08:14:04,754] {standard_task_runner.py:80} INFO - Job 3: Subtask source_ingest_sensor
[2022-10-22 08:14:04,859] {logging_mixin.py:115} WARNING - /home/***/.local/lib/python3.7/site-packages/***/models/dagrun.py:485 SAWarning: TypeDecorator UtcDateTime(timezone=True) will not produce a cache key because the ``cache_ok`` attribute is not set to True.  This can have significant performance implications including some performance degradations in comparison to prior SQLAlchemy versions.  Set this attribute to True if this type object's state is safe to use in a cache key, or False to disable this warning. (Background on this error at: https://sqlalche.me/e/14/cprf)
[2022-10-22 08:14:04,868] {task_command.py:369} INFO - Running <TaskInstance: target_ingest_dag.source_ingest_sensor scheduled__2022-10-22T07:05:00+00:00 [running]> on host b20dbd9b67c8
[2022-10-22 08:14:04,916] {logging_mixin.py:115} WARNING - /home/***/.local/lib/python3.7/site-packages/***/models/dagrun.py:485 SAWarning: TypeDecorator UtcDateTime(timezone=True) will not produce a cache key because the ``cache_ok`` attribute is not set to True.  This can have significant performance implications including some performance degradations in comparison to prior SQLAlchemy versions.  Set this attribute to True if this type object's state is safe to use in a cache key, or False to disable this warning. (Background on this error at: https://sqlalche.me/e/14/cprf)
[2022-10-22 08:14:04,990] {logging_mixin.py:115} WARNING - /home/***/.local/lib/python3.7/site-packages/***/models/renderedtifields.py:213 SAWarning: TypeDecorator UtcDateTime(timezone=True) will not produce a cache key because the ``cache_ok`` attribute is not set to True.  This can have significant performance implications including some performance degradations in comparison to prior SQLAlchemy versions.  Set this attribute to True if this type object's state is safe to use in a cache key, or False to disable this warning. (Background on this error at: https://sqlalche.me/e/14/cprf)
[2022-10-22 08:14:05,008] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=rongshiu@gmail.com
AIRFLOW_CTX_DAG_OWNER=rongshiu@gmail.com
AIRFLOW_CTX_DAG_ID=target_ingest_dag
AIRFLOW_CTX_TASK_ID=source_ingest_sensor
AIRFLOW_CTX_EXECUTION_DATE=2022-10-22T07:05:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-10-22T07:05:00+00:00
[2022-10-22 08:14:05,011] {external_task.py:166} INFO - Poking for tasks ['source_ingestion_task'] in dag source_ingest_dag on 2022-10-22T07:00:00+00:00 ... 
[2022-10-22 08:14:05,029] {logging_mixin.py:115} WARNING - /home/***/.local/lib/python3.7/site-packages/***/sensors/external_task.py:230 SAWarning: TypeDecorator UtcDateTime(timezone=True) will not produce a cache key because the ``cache_ok`` attribute is not set to True.  This can have significant performance implications including some performance degradations in comparison to prior SQLAlchemy versions.  Set this attribute to True if this type object's state is safe to use in a cache key, or False to disable this warning. (Background on this error at: https://sqlalche.me/e/14/cprf)
[2022-10-22 08:15:05,017] {external_task.py:166} INFO - Poking for tasks ['source_ingestion_task'] in dag source_ingest_dag on 2022-10-22T07:00:00+00:00 ... 
[2022-10-22 08:16:04,991] {external_task.py:166} INFO - Poking for tasks ['source_ingestion_task'] in dag source_ingest_dag on 2022-10-22T07:00:00+00:00 ... 
[2022-10-22 08:17:05,012] {external_task.py:166} INFO - Poking for tasks ['source_ingestion_task'] in dag source_ingest_dag on 2022-10-22T07:00:00+00:00 ... 
[2022-10-22 08:18:05,023] {external_task.py:166} INFO - Poking for tasks ['source_ingestion_task'] in dag source_ingest_dag on 2022-10-22T07:00:00+00:00 ... 
[2022-10-22 08:19:05,000] {external_task.py:166} INFO - Poking for tasks ['source_ingestion_task'] in dag source_ingest_dag on 2022-10-22T07:00:00+00:00 ... 
[2022-10-22 08:20:04,976] {external_task.py:166} INFO - Poking for tasks ['source_ingestion_task'] in dag source_ingest_dag on 2022-10-22T07:00:00+00:00 ... 
[2022-10-22 08:21:04,962] {external_task.py:166} INFO - Poking for tasks ['source_ingestion_task'] in dag source_ingest_dag on 2022-10-22T07:00:00+00:00 ... 
[2022-10-22 08:21:04,992] {base.py:301} INFO - Success criteria met. Exiting.
[2022-10-22 08:21:05,022] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=target_ingest_dag, task_id=source_ingest_sensor, execution_date=20221022T070500, start_date=20221022T081404, end_date=20221022T082105
[2022-10-22 08:21:05,056] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-10-22 08:21:05,122] {logging_mixin.py:115} WARNING - /home/***/.local/lib/python3.7/site-packages/***/models/taskinstance.py:2445 SAWarning: TypeDecorator UtcDateTime(timezone=True) will not produce a cache key because the ``cache_ok`` attribute is not set to True.  This can have significant performance implications including some performance degradations in comparison to prior SQLAlchemy versions.  Set this attribute to True if this type object's state is safe to use in a cache key, or False to disable this warning. (Background on this error at: https://sqlalche.me/e/14/cprf)
[2022-10-22 08:21:05,145] {local_task_job.py:273} INFO - 4 downstream tasks scheduled from follow-on schedule check
[2022-10-22 08:38:30,483] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: target_ingest_dag.source_ingest_sensor scheduled__2022-10-22T07:05:00+00:00 [queued]>
[2022-10-22 08:38:30,504] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: target_ingest_dag.source_ingest_sensor scheduled__2022-10-22T07:05:00+00:00 [queued]>
[2022-10-22 08:38:30,505] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-10-22 08:38:30,507] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2022-10-22 08:38:30,508] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-10-22 08:38:30,526] {taskinstance.py:1377} INFO - Executing <Task(ExternalTaskSensor): source_ingest_sensor> on 2022-10-22 07:05:00+00:00
[2022-10-22 08:38:30,531] {standard_task_runner.py:52} INFO - Started process 235 to run task
[2022-10-22 08:38:30,538] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'target_ingest_dag', 'source_ingest_sensor', 'scheduled__2022-10-22T07:05:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/target_ingest_dag.py', '--cfg-path', '/tmp/tmp12tobo2g', '--error-file', '/tmp/tmp8ptgph87']
[2022-10-22 08:38:30,540] {standard_task_runner.py:80} INFO - Job 3: Subtask source_ingest_sensor
[2022-10-22 08:38:30,652] {logging_mixin.py:115} WARNING - /home/***/.local/lib/python3.7/site-packages/***/models/dagrun.py:485 SAWarning: TypeDecorator UtcDateTime(timezone=True) will not produce a cache key because the ``cache_ok`` attribute is not set to True.  This can have significant performance implications including some performance degradations in comparison to prior SQLAlchemy versions.  Set this attribute to True if this type object's state is safe to use in a cache key, or False to disable this warning. (Background on this error at: https://sqlalche.me/e/14/cprf)
[2022-10-22 08:38:30,663] {task_command.py:369} INFO - Running <TaskInstance: target_ingest_dag.source_ingest_sensor scheduled__2022-10-22T07:05:00+00:00 [running]> on host 31b33e7029d2
[2022-10-22 08:38:30,712] {logging_mixin.py:115} WARNING - /home/***/.local/lib/python3.7/site-packages/***/models/dagrun.py:485 SAWarning: TypeDecorator UtcDateTime(timezone=True) will not produce a cache key because the ``cache_ok`` attribute is not set to True.  This can have significant performance implications including some performance degradations in comparison to prior SQLAlchemy versions.  Set this attribute to True if this type object's state is safe to use in a cache key, or False to disable this warning. (Background on this error at: https://sqlalche.me/e/14/cprf)
[2022-10-22 08:38:30,783] {logging_mixin.py:115} WARNING - /home/***/.local/lib/python3.7/site-packages/***/models/renderedtifields.py:213 SAWarning: TypeDecorator UtcDateTime(timezone=True) will not produce a cache key because the ``cache_ok`` attribute is not set to True.  This can have significant performance implications including some performance degradations in comparison to prior SQLAlchemy versions.  Set this attribute to True if this type object's state is safe to use in a cache key, or False to disable this warning. (Background on this error at: https://sqlalche.me/e/14/cprf)
[2022-10-22 08:38:30,796] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=rongshiu@gmail.com
AIRFLOW_CTX_DAG_OWNER=rongshiu@gmail.com
AIRFLOW_CTX_DAG_ID=target_ingest_dag
AIRFLOW_CTX_TASK_ID=source_ingest_sensor
AIRFLOW_CTX_EXECUTION_DATE=2022-10-22T07:05:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-10-22T07:05:00+00:00
[2022-10-22 08:38:30,798] {external_task.py:166} INFO - Poking for tasks ['source_ingestion_task'] in dag source_ingest_dag on 2022-10-22T07:00:00+00:00 ... 
[2022-10-22 08:38:30,812] {logging_mixin.py:115} WARNING - /home/***/.local/lib/python3.7/site-packages/***/sensors/external_task.py:230 SAWarning: TypeDecorator UtcDateTime(timezone=True) will not produce a cache key because the ``cache_ok`` attribute is not set to True.  This can have significant performance implications including some performance degradations in comparison to prior SQLAlchemy versions.  Set this attribute to True if this type object's state is safe to use in a cache key, or False to disable this warning. (Background on this error at: https://sqlalche.me/e/14/cprf)
[2022-10-22 08:39:18,356] {local_task_job.py:84} ERROR - Received SIGTERM. Terminating subprocesses
[2022-10-22 08:39:18,389] {process_utils.py:129} INFO - Sending Signals.SIGTERM to group 235. PIDs of all processes in the group: [235]
[2022-10-22 08:39:18,399] {process_utils.py:80} INFO - Sending the signal Signals.SIGTERM to group 235
[2022-10-22 08:39:18,405] {taskinstance.py:1541} ERROR - Received SIGTERM. Terminating subprocesses.
[2022-10-22 08:39:20,120] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/sensors/base.py", line 299, in execute
    time.sleep(self._get_next_poke_interval(started_at, run_duration, try_number))
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1543, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2022-10-22 08:39:20,144] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=target_ingest_dag, task_id=source_ingest_sensor, execution_date=20221022T070500, start_date=20221022T083830, end_date=20221022T083920
[2022-10-22 08:39:20,240] {standard_task_runner.py:97} ERROR - Failed to execute job 3 for task source_ingest_sensor (Task received SIGTERM signal; 235)
[2022-10-22 08:39:20,327] {process_utils.py:75} INFO - Process psutil.Process(pid=235, status='terminated', exitcode=1, started='08:38:30') (235) terminated with exit code 1
[2022-10-22 08:39:20,332] {local_task_job.py:156} INFO - Task exited with return code 143
[2022-10-22 08:39:20,488] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-10-22 08:49:39,876] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: target_ingest_dag.source_ingest_sensor scheduled__2022-10-22T07:05:00+00:00 [queued]>
[2022-10-22 08:49:39,893] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: target_ingest_dag.source_ingest_sensor scheduled__2022-10-22T07:05:00+00:00 [queued]>
[2022-10-22 08:49:39,895] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-10-22 08:49:39,896] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2022-10-22 08:49:39,897] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-10-22 08:49:39,915] {taskinstance.py:1377} INFO - Executing <Task(ExternalTaskSensor): source_ingest_sensor> on 2022-10-22 07:05:00+00:00
[2022-10-22 08:49:39,923] {standard_task_runner.py:52} INFO - Started process 390 to run task
[2022-10-22 08:49:39,927] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'target_ingest_dag', 'source_ingest_sensor', 'scheduled__2022-10-22T07:05:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/target_ingest_dag.py', '--cfg-path', '/tmp/tmpzdk70xy0', '--error-file', '/tmp/tmpzsb4by6n']
[2022-10-22 08:49:39,929] {standard_task_runner.py:80} INFO - Job 3: Subtask source_ingest_sensor
[2022-10-22 08:49:40,027] {logging_mixin.py:115} WARNING - /home/***/.local/lib/python3.7/site-packages/***/models/dagrun.py:485 SAWarning: TypeDecorator UtcDateTime(timezone=True) will not produce a cache key because the ``cache_ok`` attribute is not set to True.  This can have significant performance implications including some performance degradations in comparison to prior SQLAlchemy versions.  Set this attribute to True if this type object's state is safe to use in a cache key, or False to disable this warning. (Background on this error at: https://sqlalche.me/e/14/cprf)
[2022-10-22 08:49:40,051] {task_command.py:369} INFO - Running <TaskInstance: target_ingest_dag.source_ingest_sensor scheduled__2022-10-22T07:05:00+00:00 [running]> on host 5ff5881c9478
[2022-10-22 08:49:40,158] {logging_mixin.py:115} WARNING - /home/***/.local/lib/python3.7/site-packages/***/models/dagrun.py:485 SAWarning: TypeDecorator UtcDateTime(timezone=True) will not produce a cache key because the ``cache_ok`` attribute is not set to True.  This can have significant performance implications including some performance degradations in comparison to prior SQLAlchemy versions.  Set this attribute to True if this type object's state is safe to use in a cache key, or False to disable this warning. (Background on this error at: https://sqlalche.me/e/14/cprf)
[2022-10-22 08:49:40,247] {logging_mixin.py:115} WARNING - /home/***/.local/lib/python3.7/site-packages/***/models/renderedtifields.py:213 SAWarning: TypeDecorator UtcDateTime(timezone=True) will not produce a cache key because the ``cache_ok`` attribute is not set to True.  This can have significant performance implications including some performance degradations in comparison to prior SQLAlchemy versions.  Set this attribute to True if this type object's state is safe to use in a cache key, or False to disable this warning. (Background on this error at: https://sqlalche.me/e/14/cprf)
[2022-10-22 08:49:40,263] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=rongshiu@gmail.com
AIRFLOW_CTX_DAG_OWNER=rongshiu@gmail.com
AIRFLOW_CTX_DAG_ID=target_ingest_dag
AIRFLOW_CTX_TASK_ID=source_ingest_sensor
AIRFLOW_CTX_EXECUTION_DATE=2022-10-22T07:05:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-10-22T07:05:00+00:00
[2022-10-22 08:49:40,267] {external_task.py:166} INFO - Poking for tasks ['source_ingestion_task'] in dag source_ingest_dag on 2022-10-22T07:00:00+00:00 ... 
[2022-10-22 08:49:40,282] {logging_mixin.py:115} WARNING - /home/***/.local/lib/python3.7/site-packages/***/sensors/external_task.py:230 SAWarning: TypeDecorator UtcDateTime(timezone=True) will not produce a cache key because the ``cache_ok`` attribute is not set to True.  This can have significant performance implications including some performance degradations in comparison to prior SQLAlchemy versions.  Set this attribute to True if this type object's state is safe to use in a cache key, or False to disable this warning. (Background on this error at: https://sqlalche.me/e/14/cprf)
[2022-10-22 08:50:20,203] {local_task_job.py:84} ERROR - Received SIGTERM. Terminating subprocesses
[2022-10-22 08:50:20,220] {process_utils.py:129} INFO - Sending Signals.SIGTERM to group 390. PIDs of all processes in the group: [390]
[2022-10-22 08:50:20,226] {process_utils.py:80} INFO - Sending the signal Signals.SIGTERM to group 390
[2022-10-22 08:50:20,229] {taskinstance.py:1541} ERROR - Received SIGTERM. Terminating subprocesses.
[2022-10-22 08:50:20,343] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/sensors/base.py", line 299, in execute
    time.sleep(self._get_next_poke_interval(started_at, run_duration, try_number))
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1543, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2022-10-22 08:50:20,370] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=target_ingest_dag, task_id=source_ingest_sensor, execution_date=20221022T070500, start_date=20221022T084939, end_date=20221022T085020
[2022-10-22 08:50:20,442] {standard_task_runner.py:97} ERROR - Failed to execute job 3 for task source_ingest_sensor (Task received SIGTERM signal; 390)
[2022-10-22 08:50:20,504] {process_utils.py:75} INFO - Process psutil.Process(pid=390, status='terminated', exitcode=1, started='08:49:39') (390) terminated with exit code 1
[2022-10-22 08:50:20,507] {local_task_job.py:156} INFO - Task exited with return code 143
[2022-10-22 08:50:20,734] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-10-22 08:52:25,259] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: target_ingest_dag.source_ingest_sensor scheduled__2022-10-22T07:05:00+00:00 [queued]>
[2022-10-22 08:52:25,278] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: target_ingest_dag.source_ingest_sensor scheduled__2022-10-22T07:05:00+00:00 [queued]>
[2022-10-22 08:52:25,279] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-10-22 08:52:25,281] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2022-10-22 08:52:25,281] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-10-22 08:52:25,300] {taskinstance.py:1377} INFO - Executing <Task(ExternalTaskSensor): source_ingest_sensor> on 2022-10-22 07:05:00+00:00
[2022-10-22 08:52:25,312] {standard_task_runner.py:52} INFO - Started process 225 to run task
[2022-10-22 08:52:25,315] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'target_ingest_dag', 'source_ingest_sensor', 'scheduled__2022-10-22T07:05:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/target_ingest_dag.py', '--cfg-path', '/tmp/tmp41gopgfn', '--error-file', '/tmp/tmp2y761wle']
[2022-10-22 08:52:25,318] {standard_task_runner.py:80} INFO - Job 3: Subtask source_ingest_sensor
[2022-10-22 08:52:25,426] {logging_mixin.py:115} WARNING - /home/***/.local/lib/python3.7/site-packages/***/models/dagrun.py:485 SAWarning: TypeDecorator UtcDateTime(timezone=True) will not produce a cache key because the ``cache_ok`` attribute is not set to True.  This can have significant performance implications including some performance degradations in comparison to prior SQLAlchemy versions.  Set this attribute to True if this type object's state is safe to use in a cache key, or False to disable this warning. (Background on this error at: https://sqlalche.me/e/14/cprf)
[2022-10-22 08:52:25,438] {task_command.py:369} INFO - Running <TaskInstance: target_ingest_dag.source_ingest_sensor scheduled__2022-10-22T07:05:00+00:00 [running]> on host 236209f5c3f9
[2022-10-22 08:52:25,495] {logging_mixin.py:115} WARNING - /home/***/.local/lib/python3.7/site-packages/***/models/dagrun.py:485 SAWarning: TypeDecorator UtcDateTime(timezone=True) will not produce a cache key because the ``cache_ok`` attribute is not set to True.  This can have significant performance implications including some performance degradations in comparison to prior SQLAlchemy versions.  Set this attribute to True if this type object's state is safe to use in a cache key, or False to disable this warning. (Background on this error at: https://sqlalche.me/e/14/cprf)
[2022-10-22 08:52:25,573] {logging_mixin.py:115} WARNING - /home/***/.local/lib/python3.7/site-packages/***/models/renderedtifields.py:213 SAWarning: TypeDecorator UtcDateTime(timezone=True) will not produce a cache key because the ``cache_ok`` attribute is not set to True.  This can have significant performance implications including some performance degradations in comparison to prior SQLAlchemy versions.  Set this attribute to True if this type object's state is safe to use in a cache key, or False to disable this warning. (Background on this error at: https://sqlalche.me/e/14/cprf)
[2022-10-22 08:52:25,593] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=rongshiu@gmail.com
AIRFLOW_CTX_DAG_OWNER=rongshiu@gmail.com
AIRFLOW_CTX_DAG_ID=target_ingest_dag
AIRFLOW_CTX_TASK_ID=source_ingest_sensor
AIRFLOW_CTX_EXECUTION_DATE=2022-10-22T07:05:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-10-22T07:05:00+00:00
[2022-10-22 08:52:25,595] {external_task.py:166} INFO - Poking for tasks ['source_ingestion_task'] in dag source_ingest_dag on 2022-10-22T07:00:00+00:00 ... 
[2022-10-22 08:52:25,609] {logging_mixin.py:115} WARNING - /home/***/.local/lib/python3.7/site-packages/***/sensors/external_task.py:230 SAWarning: TypeDecorator UtcDateTime(timezone=True) will not produce a cache key because the ``cache_ok`` attribute is not set to True.  This can have significant performance implications including some performance degradations in comparison to prior SQLAlchemy versions.  Set this attribute to True if this type object's state is safe to use in a cache key, or False to disable this warning. (Background on this error at: https://sqlalche.me/e/14/cprf)
[2022-10-22 08:53:25,612] {external_task.py:166} INFO - Poking for tasks ['source_ingestion_task'] in dag source_ingest_dag on 2022-10-22T07:00:00+00:00 ... 
[2022-10-22 08:54:25,609] {external_task.py:166} INFO - Poking for tasks ['source_ingestion_task'] in dag source_ingest_dag on 2022-10-22T07:00:00+00:00 ... 
[2022-10-22 08:55:25,579] {external_task.py:166} INFO - Poking for tasks ['source_ingestion_task'] in dag source_ingest_dag on 2022-10-22T07:00:00+00:00 ... 
[2022-10-22 08:56:25,587] {external_task.py:166} INFO - Poking for tasks ['source_ingestion_task'] in dag source_ingest_dag on 2022-10-22T07:00:00+00:00 ... 
[2022-10-22 08:57:25,552] {external_task.py:166} INFO - Poking for tasks ['source_ingestion_task'] in dag source_ingest_dag on 2022-10-22T07:00:00+00:00 ... 
[2022-10-22 08:58:25,609] {external_task.py:166} INFO - Poking for tasks ['source_ingestion_task'] in dag source_ingest_dag on 2022-10-22T07:00:00+00:00 ... 
[2022-10-22 08:58:25,652] {base.py:301} INFO - Success criteria met. Exiting.
[2022-10-22 08:58:25,678] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=target_ingest_dag, task_id=source_ingest_sensor, execution_date=20221022T070500, start_date=20221022T085225, end_date=20221022T085825
[2022-10-22 08:58:25,742] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-10-22 08:58:25,821] {logging_mixin.py:115} WARNING - /home/***/.local/lib/python3.7/site-packages/***/models/taskinstance.py:2445 SAWarning: TypeDecorator UtcDateTime(timezone=True) will not produce a cache key because the ``cache_ok`` attribute is not set to True.  This can have significant performance implications including some performance degradations in comparison to prior SQLAlchemy versions.  Set this attribute to True if this type object's state is safe to use in a cache key, or False to disable this warning. (Background on this error at: https://sqlalche.me/e/14/cprf)
[2022-10-22 08:58:25,850] {local_task_job.py:273} INFO - 4 downstream tasks scheduled from follow-on schedule check
