[2022-10-22 10:10:53,850] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: target_ingest_dag.source_ingest_sensor scheduled__2022-10-22T09:05:00+00:00 [queued]>
[2022-10-22 10:10:53,868] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: target_ingest_dag.source_ingest_sensor scheduled__2022-10-22T09:05:00+00:00 [queued]>
[2022-10-22 10:10:53,870] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-10-22 10:10:53,871] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2022-10-22 10:10:53,872] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-10-22 10:10:53,893] {taskinstance.py:1377} INFO - Executing <Task(ExternalTaskSensor): source_ingest_sensor> on 2022-10-22 09:05:00+00:00
[2022-10-22 10:10:53,903] {standard_task_runner.py:52} INFO - Started process 883 to run task
[2022-10-22 10:10:53,907] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'target_ingest_dag', 'source_ingest_sensor', 'scheduled__2022-10-22T09:05:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/target_ingest_dag.py', '--cfg-path', '/tmp/tmp3bpl5n6q', '--error-file', '/tmp/tmpa5_vxcmu']
[2022-10-22 10:10:53,909] {standard_task_runner.py:80} INFO - Job 3: Subtask source_ingest_sensor
[2022-10-22 10:10:54,006] {logging_mixin.py:115} WARNING - /home/***/.local/lib/python3.7/site-packages/***/models/dagrun.py:485 SAWarning: TypeDecorator UtcDateTime(timezone=True) will not produce a cache key because the ``cache_ok`` attribute is not set to True.  This can have significant performance implications including some performance degradations in comparison to prior SQLAlchemy versions.  Set this attribute to True if this type object's state is safe to use in a cache key, or False to disable this warning. (Background on this error at: https://sqlalche.me/e/14/cprf)
[2022-10-22 10:10:54,017] {task_command.py:369} INFO - Running <TaskInstance: target_ingest_dag.source_ingest_sensor scheduled__2022-10-22T09:05:00+00:00 [running]> on host d162a828b547
[2022-10-22 10:10:54,080] {logging_mixin.py:115} WARNING - /home/***/.local/lib/python3.7/site-packages/***/models/dagrun.py:485 SAWarning: TypeDecorator UtcDateTime(timezone=True) will not produce a cache key because the ``cache_ok`` attribute is not set to True.  This can have significant performance implications including some performance degradations in comparison to prior SQLAlchemy versions.  Set this attribute to True if this type object's state is safe to use in a cache key, or False to disable this warning. (Background on this error at: https://sqlalche.me/e/14/cprf)
[2022-10-22 10:10:54,171] {logging_mixin.py:115} WARNING - /home/***/.local/lib/python3.7/site-packages/***/models/renderedtifields.py:213 SAWarning: TypeDecorator UtcDateTime(timezone=True) will not produce a cache key because the ``cache_ok`` attribute is not set to True.  This can have significant performance implications including some performance degradations in comparison to prior SQLAlchemy versions.  Set this attribute to True if this type object's state is safe to use in a cache key, or False to disable this warning. (Background on this error at: https://sqlalche.me/e/14/cprf)
[2022-10-22 10:10:54,196] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=rongshiu@gmail.com
AIRFLOW_CTX_DAG_OWNER=rongshiu@gmail.com
AIRFLOW_CTX_DAG_ID=target_ingest_dag
AIRFLOW_CTX_TASK_ID=source_ingest_sensor
AIRFLOW_CTX_EXECUTION_DATE=2022-10-22T09:05:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-10-22T09:05:00+00:00
[2022-10-22 10:10:54,203] {external_task.py:166} INFO - Poking for tasks ['source_ingestion_task'] in dag source_ingest_dag on 2022-10-22T09:00:00+00:00 ... 
[2022-10-22 10:10:54,231] {logging_mixin.py:115} WARNING - /home/***/.local/lib/python3.7/site-packages/***/sensors/external_task.py:230 SAWarning: TypeDecorator UtcDateTime(timezone=True) will not produce a cache key because the ``cache_ok`` attribute is not set to True.  This can have significant performance implications including some performance degradations in comparison to prior SQLAlchemy versions.  Set this attribute to True if this type object's state is safe to use in a cache key, or False to disable this warning. (Background on this error at: https://sqlalche.me/e/14/cprf)
[2022-10-22 10:11:54,218] {external_task.py:166} INFO - Poking for tasks ['source_ingestion_task'] in dag source_ingest_dag on 2022-10-22T09:00:00+00:00 ... 
[2022-10-22 10:12:54,222] {external_task.py:166} INFO - Poking for tasks ['source_ingestion_task'] in dag source_ingest_dag on 2022-10-22T09:00:00+00:00 ... 
[2022-10-22 10:13:54,195] {external_task.py:166} INFO - Poking for tasks ['source_ingestion_task'] in dag source_ingest_dag on 2022-10-22T09:00:00+00:00 ... 
[2022-10-22 10:14:54,201] {external_task.py:166} INFO - Poking for tasks ['source_ingestion_task'] in dag source_ingest_dag on 2022-10-22T09:00:00+00:00 ... 
[2022-10-22 10:15:54,196] {external_task.py:166} INFO - Poking for tasks ['source_ingestion_task'] in dag source_ingest_dag on 2022-10-22T09:00:00+00:00 ... 
[2022-10-22 10:16:25,287] {local_task_job.py:84} ERROR - Received SIGTERM. Terminating subprocesses
[2022-10-22 10:16:25,743] {process_utils.py:129} INFO - Sending Signals.SIGTERM to group 883. PIDs of all processes in the group: [883]
[2022-10-22 10:16:25,746] {process_utils.py:80} INFO - Sending the signal Signals.SIGTERM to group 883
[2022-10-22 10:16:25,751] {taskinstance.py:1541} ERROR - Received SIGTERM. Terminating subprocesses.
[2022-10-22 10:16:25,863] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/sensors/base.py", line 299, in execute
    time.sleep(self._get_next_poke_interval(started_at, run_duration, try_number))
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1543, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2022-10-22 10:16:25,887] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=target_ingest_dag, task_id=source_ingest_sensor, execution_date=20221022T090500, start_date=20221022T101053, end_date=20221022T101625
[2022-10-22 10:16:25,968] {standard_task_runner.py:97} ERROR - Failed to execute job 3 for task source_ingest_sensor (Task received SIGTERM signal; 883)
[2022-10-22 10:16:25,988] {process_utils.py:75} INFO - Process psutil.Process(pid=883, status='terminated', exitcode=1, started='10:10:53') (883) terminated with exit code 1
[2022-10-22 10:16:25,990] {local_task_job.py:156} INFO - Task exited with return code 143
[2022-10-22 10:16:26,144] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
