[2022-10-22 08:21:06,801] {logging_mixin.py:115} WARNING - /home/***/.local/lib/python3.7/site-packages/***/models/taskinstance.py:2445 SAWarning: TypeDecorator UtcDateTime(timezone=True) will not produce a cache key because the ``cache_ok`` attribute is not set to True.  This can have significant performance implications including some performance degradations in comparison to prior SQLAlchemy versions.  Set this attribute to True if this type object's state is safe to use in a cache key, or False to disable this warning. (Background on this error at: https://sqlalche.me/e/14/cprf)
[2022-10-22 08:21:06,811] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: target_ingest_dag.target_ingestion_task_2a scheduled__2022-10-22T07:05:00+00:00 [queued]>
[2022-10-22 08:21:06,833] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: target_ingest_dag.target_ingestion_task_2a scheduled__2022-10-22T07:05:00+00:00 [queued]>
[2022-10-22 08:21:06,835] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-10-22 08:21:06,836] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2022-10-22 08:21:06,837] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-10-22 08:21:06,854] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): target_ingestion_task_2a> on 2022-10-22 07:05:00+00:00
[2022-10-22 08:21:06,860] {standard_task_runner.py:52} INFO - Started process 378 to run task
[2022-10-22 08:21:06,864] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'target_ingest_dag', 'target_ingestion_task_2a', 'scheduled__2022-10-22T07:05:00+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/target_ingest_dag.py', '--cfg-path', '/tmp/tmp1bb_8b9e', '--error-file', '/tmp/tmpm2agantk']
[2022-10-22 08:21:06,866] {standard_task_runner.py:80} INFO - Job 4: Subtask target_ingestion_task_2a
[2022-10-22 08:21:06,999] {logging_mixin.py:115} WARNING - /home/***/.local/lib/python3.7/site-packages/***/models/dagrun.py:485 SAWarning: TypeDecorator UtcDateTime(timezone=True) will not produce a cache key because the ``cache_ok`` attribute is not set to True.  This can have significant performance implications including some performance degradations in comparison to prior SQLAlchemy versions.  Set this attribute to True if this type object's state is safe to use in a cache key, or False to disable this warning. (Background on this error at: https://sqlalche.me/e/14/cprf)
[2022-10-22 08:21:07,007] {task_command.py:369} INFO - Running <TaskInstance: target_ingest_dag.target_ingestion_task_2a scheduled__2022-10-22T07:05:00+00:00 [running]> on host b20dbd9b67c8
[2022-10-22 08:21:07,060] {logging_mixin.py:115} WARNING - /home/***/.local/lib/python3.7/site-packages/***/models/dagrun.py:485 SAWarning: TypeDecorator UtcDateTime(timezone=True) will not produce a cache key because the ``cache_ok`` attribute is not set to True.  This can have significant performance implications including some performance degradations in comparison to prior SQLAlchemy versions.  Set this attribute to True if this type object's state is safe to use in a cache key, or False to disable this warning. (Background on this error at: https://sqlalche.me/e/14/cprf)
[2022-10-22 08:21:07,213] {logging_mixin.py:115} WARNING - /home/***/.local/lib/python3.7/site-packages/***/models/renderedtifields.py:213 SAWarning: TypeDecorator UtcDateTime(timezone=True) will not produce a cache key because the ``cache_ok`` attribute is not set to True.  This can have significant performance implications including some performance degradations in comparison to prior SQLAlchemy versions.  Set this attribute to True if this type object's state is safe to use in a cache key, or False to disable this warning. (Background on this error at: https://sqlalche.me/e/14/cprf)
[2022-10-22 08:21:07,243] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=rongshiu@gmail.com
AIRFLOW_CTX_DAG_OWNER=rongshiu@gmail.com
AIRFLOW_CTX_DAG_ID=target_ingest_dag
AIRFLOW_CTX_TASK_ID=target_ingestion_task_2a
AIRFLOW_CTX_EXECUTION_DATE=2022-10-22T07:05:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-10-22T07:05:00+00:00
[2022-10-22 08:21:07,247] {target_ingest.py:10} INFO - Reading SQL file from path
[2022-10-22 08:21:07,249] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/opt/airflow/dags/target_ingest.py", line 11, in target_ingest
    query = open(sql_path, 'r')
FileNotFoundError: [Errno 2] No such file or directory: '/sources/dags/2a.sql'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/target_ingest.py", line 28, in target_ingest
    logger.error('target_ingest pipeline failed due to {error}',error=e)
  File "/usr/local/lib/python3.7/logging/__init__.py", line 1407, in error
    self._log(ERROR, msg, args, **kwargs)
TypeError: _log() got an unexpected keyword argument 'error'
[2022-10-22 08:21:07,306] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=target_ingest_dag, task_id=target_ingestion_task_2a, execution_date=20221022T070500, start_date=20221022T082106, end_date=20221022T082107
[2022-10-22 08:21:07,342] {standard_task_runner.py:97} ERROR - Failed to execute job 4 for task target_ingestion_task_2a (_log() got an unexpected keyword argument 'error'; 378)
[2022-10-22 08:21:07,367] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-10-22 08:21:07,467] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-10-22 08:58:28,400] {logging_mixin.py:115} WARNING - /home/***/.local/lib/python3.7/site-packages/***/models/taskinstance.py:2445 SAWarning: TypeDecorator UtcDateTime(timezone=True) will not produce a cache key because the ``cache_ok`` attribute is not set to True.  This can have significant performance implications including some performance degradations in comparison to prior SQLAlchemy versions.  Set this attribute to True if this type object's state is safe to use in a cache key, or False to disable this warning. (Background on this error at: https://sqlalche.me/e/14/cprf)
[2022-10-22 08:58:28,415] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: target_ingest_dag.target_ingestion_task_2a scheduled__2022-10-22T07:05:00+00:00 [queued]>
[2022-10-22 08:58:28,450] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: target_ingest_dag.target_ingestion_task_2a scheduled__2022-10-22T07:05:00+00:00 [queued]>
[2022-10-22 08:58:28,451] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-10-22 08:58:28,453] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2022-10-22 08:58:28,454] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-10-22 08:58:28,485] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): target_ingestion_task_2a> on 2022-10-22 07:05:00+00:00
[2022-10-22 08:58:28,497] {standard_task_runner.py:52} INFO - Started process 369 to run task
[2022-10-22 08:58:28,506] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'target_ingest_dag', 'target_ingestion_task_2a', 'scheduled__2022-10-22T07:05:00+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/target_ingest_dag.py', '--cfg-path', '/tmp/tmp3leteeqz', '--error-file', '/tmp/tmpcbs88qon']
[2022-10-22 08:58:28,513] {standard_task_runner.py:80} INFO - Job 7: Subtask target_ingestion_task_2a
[2022-10-22 08:58:28,701] {logging_mixin.py:115} WARNING - /home/***/.local/lib/python3.7/site-packages/***/models/dagrun.py:485 SAWarning: TypeDecorator UtcDateTime(timezone=True) will not produce a cache key because the ``cache_ok`` attribute is not set to True.  This can have significant performance implications including some performance degradations in comparison to prior SQLAlchemy versions.  Set this attribute to True if this type object's state is safe to use in a cache key, or False to disable this warning. (Background on this error at: https://sqlalche.me/e/14/cprf)
[2022-10-22 08:58:28,716] {task_command.py:369} INFO - Running <TaskInstance: target_ingest_dag.target_ingestion_task_2a scheduled__2022-10-22T07:05:00+00:00 [running]> on host 236209f5c3f9
[2022-10-22 08:58:28,778] {logging_mixin.py:115} WARNING - /home/***/.local/lib/python3.7/site-packages/***/models/dagrun.py:485 SAWarning: TypeDecorator UtcDateTime(timezone=True) will not produce a cache key because the ``cache_ok`` attribute is not set to True.  This can have significant performance implications including some performance degradations in comparison to prior SQLAlchemy versions.  Set this attribute to True if this type object's state is safe to use in a cache key, or False to disable this warning. (Background on this error at: https://sqlalche.me/e/14/cprf)
[2022-10-22 08:58:28,881] {logging_mixin.py:115} WARNING - /home/***/.local/lib/python3.7/site-packages/***/models/renderedtifields.py:213 SAWarning: TypeDecorator UtcDateTime(timezone=True) will not produce a cache key because the ``cache_ok`` attribute is not set to True.  This can have significant performance implications including some performance degradations in comparison to prior SQLAlchemy versions.  Set this attribute to True if this type object's state is safe to use in a cache key, or False to disable this warning. (Background on this error at: https://sqlalche.me/e/14/cprf)
[2022-10-22 08:58:28,898] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=rongshiu@gmail.com
AIRFLOW_CTX_DAG_OWNER=rongshiu@gmail.com
AIRFLOW_CTX_DAG_ID=target_ingest_dag
AIRFLOW_CTX_TASK_ID=target_ingestion_task_2a
AIRFLOW_CTX_EXECUTION_DATE=2022-10-22T07:05:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-10-22T07:05:00+00:00
[2022-10-22 08:58:28,900] {target_ingest.py:10} INFO - Reading SQL file from path
[2022-10-22 08:58:28,906] {target_ingest.py:12} INFO - Read SQL file process completed
[2022-10-22 08:58:28,910] {target_ingest.py:15} INFO - Getting data from source_db
[2022-10-22 08:58:29,819] {target_ingest.py:17} INFO - Successfully get data from source_db
[2022-10-22 08:58:29,822] {target_ingest.py:22} INFO - Uploading data to target_db
[2022-10-22 08:58:29,917] {target_ingest.py:26} INFO - Successfully uploaded data to target_db
[2022-10-22 08:58:29,919] {python.py:173} INFO - Done. Returned value was: None
[2022-10-22 08:58:29,947] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=target_ingest_dag, task_id=target_ingestion_task_2a, execution_date=20221022T070500, start_date=20221022T085828, end_date=20221022T085829
[2022-10-22 08:58:29,987] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-10-22 08:58:30,053] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
