[2022-10-22 08:00:30,015] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: source_ingest_dag.source_ingestion_task manual__2022-10-22T08:00:27.625739+00:00 [queued]>
[2022-10-22 08:00:30,034] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: source_ingest_dag.source_ingestion_task manual__2022-10-22T08:00:27.625739+00:00 [queued]>
[2022-10-22 08:00:30,035] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-10-22 08:00:30,036] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2022-10-22 08:00:30,038] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-10-22 08:00:30,057] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): source_ingestion_task> on 2022-10-22 08:00:27.625739+00:00
[2022-10-22 08:00:30,064] {standard_task_runner.py:52} INFO - Started process 207 to run task
[2022-10-22 08:00:30,068] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'source_ingest_dag', 'source_ingestion_task', 'manual__2022-10-22T08:00:27.625739+00:00', '--job-id', '2', '--raw', '--subdir', 'DAGS_FOLDER/source_ingest_dag.py', '--cfg-path', '/tmp/tmpg42v5zum', '--error-file', '/tmp/tmpevlzu55e']
[2022-10-22 08:00:30,070] {standard_task_runner.py:80} INFO - Job 2: Subtask source_ingestion_task
[2022-10-22 08:00:30,182] {task_command.py:369} INFO - Running <TaskInstance: source_ingest_dag.source_ingestion_task manual__2022-10-22T08:00:27.625739+00:00 [running]> on host 66c339828860
[2022-10-22 08:00:30,312] {logging_mixin.py:115} WARNING - /home/***/.local/lib/python3.7/site-packages/***/models/renderedtifields.py:213 SAWarning: TypeDecorator UtcDateTime(timezone=True) will not produce a cache key because the ``cache_ok`` attribute is not set to True.  This can have significant performance implications including some performance degradations in comparison to prior SQLAlchemy versions.  Set this attribute to True if this type object's state is safe to use in a cache key, or False to disable this warning. (Background on this error at: https://sqlalche.me/e/14/cprf)
[2022-10-22 08:00:30,332] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=rongshiu@gmail.com
AIRFLOW_CTX_DAG_OWNER=rongshiu@gmail.com
AIRFLOW_CTX_DAG_ID=source_ingest_dag
AIRFLOW_CTX_TASK_ID=source_ingestion_task
AIRFLOW_CTX_EXECUTION_DATE=2022-10-22T08:00:27.625739+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-10-22T08:00:27.625739+00:00
[2022-10-22 08:00:30,334] {source_ingest.py:9} INFO - Getting source data
[2022-10-22 08:01:01,015] {source_ingest.py:13} INFO - Successfully get source data
[2022-10-22 08:01:01,027] {source_ingest.py:19} INFO - Uploading source data
[2022-10-22 08:06:16,606] {source_ingest.py:23} INFO - Successfully uploaded source data
[2022-10-22 08:06:16,628] {python.py:173} INFO - Done. Returned value was: None
[2022-10-22 08:06:16,656] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=source_ingest_dag, task_id=source_ingestion_task, execution_date=20221022T080027, start_date=20221022T080030, end_date=20221022T080616
[2022-10-22 08:06:16,736] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-10-22 08:06:16,798] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
